import type { ThemeColorRole } from './create-theme.js';

/**
 * Canonical Material light-scheme fallbacks aligned with `@m3ui/tokens` codegen
 * (`--md-sys-color-*: var(--m3-color-*, <fallback>)` on `:root`).
 */
export const COLOR_FALLBACKS: Record<ThemeColorRole, string> = {
  primary: '#6750a4',
  onPrimary: '#ffffff',
  primaryContainer: '#eaddff',
  onPrimaryContainer: '#4f378a',
  primaryFixed: '#eaddff',
  primaryFixedDim: '#d0bcff',
  onPrimaryFixed: '#21005d',
  onPrimaryFixedVariant: '#4f378b',
  secondary: '#625b71',
  onSecondary: '#ffffff',
  secondaryContainer: '#e8def8',
  onSecondaryContainer: '#4a4459',
  secondaryFixed: '#e8def8',
  secondaryFixedDim: '#ccc2dc',
  onSecondaryFixed: '#1d192b',
  onSecondaryFixedVariant: '#4a4458',
  tertiary: '#7d5260',
  onTertiary: '#ffffff',
  tertiaryContainer: '#ffd8e4',
  onTertiaryContainer: '#633b48',
  tertiaryFixed: '#ffd8e4',
  tertiaryFixedDim: '#efb8c8',
  onTertiaryFixed: '#31111d',
  onTertiaryFixedVariant: '#633b48',
  error: '#b3261e',
  onError: '#ffffff',
  errorContainer: '#f9dedc',
  onErrorContainer: '#852221',
  background: '#fef7ff',
  onBackground: '#1d1b20',
  surface: '#fef7ff',
  onSurface: '#1d1b20',
  surfaceVariant: '#e7e0ec',
  onSurfaceVariant: '#49454f',
  surfaceTint: '#6750a4',
  outline: '#79747e',
  outlineVariant: '#cac4d0',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#322f35',
  inverseOnSurface: '#f5eff7',
  inversePrimary: '#d0bcff',
  surfaceDim: '#ded8e1',
  surfaceBright: '#fef7ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f7f2fa',
  surfaceContainer: '#f3edf7',
  surfaceContainerHigh: '#ece6f0',
  surfaceContainerHighest: '#e6e0e9',
};
