import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const STORYBOOK_ROOT = join(__dirname, '..');
const REPO_ROOT = join(STORYBOOK_ROOT, '../..');
const GENERATED_DIR = join(STORYBOOK_ROOT, 'src/stories/generated');
const DOCS_CATALOG_PATH = join(REPO_ROOT, 'packages/react/registry/docs-catalog.json');
const EXAMPLES_INDEX_PATH = join(REPO_ROOT, 'packages/examples/src/examples-map.ts');

const CATEGORY_LABELS = {
  actions: 'Actions',
  inputs: 'Inputs',
  selection: 'Selection',
  communication: 'Communication',
  containment: 'Containment',
  navigation: 'Navigation',
  feedback: 'Feedback',
  pickers: 'Pickers',
  layout: 'Layout',
};

function loadDocsCatalog() {
  const raw = readFileSync(DOCS_CATALOG_PATH, 'utf8');
  const manifest = JSON.parse(raw);
  return manifest.entries.filter(
    (entry) => entry.registryType === 'registry:ui' && entry.docs?.publicIndex === true,
  );
}

function loadSharedExampleSlugs() {
  const source = readFileSync(EXAMPLES_INDEX_PATH, 'utf8');
  const block = source.match(/EXAMPLES_BY_SLUG[^=]*=\s*\{([\s\S]*?)\};/);
  if (!block) {
    return new Set();
  }

  const slugs = [];
  for (const match of block[1].matchAll(/^\s+['"]?([\w-]+)['"]?\s*:/gm)) {
    slugs.push(match[1]);
  }
  return new Set(slugs);
}

function slugToExampleName(slug) {
  const pascal = slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  return `${pascal}Example`;
}

function toStoryExportName(title, index) {
  const sanitized = title.replace(/[^a-zA-Z0-9]/g, '');
  if (!sanitized) {
    return `Example${index}`;
  }
  if (/^\d/.test(sanitized)) {
    return `Example${sanitized}`;
  }
  return sanitized;
}

function renderSharedExampleStoryFile(entry, sharedExamples) {
  const category = CATEGORY_LABELS[entry.category] ?? entry.category;
  const storyExports = sharedExamples
    .map((example, index) => {
      const exportName = toStoryExportName(example.title, index);
      return `
export const ${exportName}: Story = {
  name: ${JSON.stringify(example.title)},
  render: () => {
    const Example = examples[${index}]!.Component;
    return <Example />;
  },
};`;
    })
    .join('\n');

  const defaultPlay =
    sharedExamples.length > 0
      ? `
export const SmokeTest: Story = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    await expect(canvasElement.firstChild).toBeTruthy();
  },
};`
      : '';

  return `/* eslint-disable -- generated by scripts/generate-stories.mjs */
import type { Meta, StoryObj } from '@storybook/react';
import { expect, within } from '@storybook/test';
import { getExamplesForSlug } from '@m3ui/examples';

const examples = getExamplesForSlug(${JSON.stringify(entry.slug)});

const meta = {
  title: '${category}/${entry.title}',
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component: ${JSON.stringify(entry.description)},
      },
    },
  },
} satisfies Meta;

export default meta;

type Story = StoryObj<typeof meta>;
${storyExports}
${defaultPlay}
`;
}

function renderLegacyStoryFile(entry) {
  const category = CATEGORY_LABELS[entry.category] ?? entry.category;
  const example = slugToExampleName(entry.slug);

  return `/* eslint-disable -- generated by scripts/generate-stories.mjs */
import type { Meta, StoryObj } from '@storybook/react';
import { expect, within } from '@storybook/test';
import { ${example} } from '../../examples/components.js';

const meta = {
  title: '${category}/${entry.title}',
  component: ${example},
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component: ${JSON.stringify(entry.description)},
      },
    },
  },
} satisfies Meta<typeof ${example}>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const Interaction: Story = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    await expect(canvas.getByRole('heading', { level: 2 })).toBeVisible();
  },
};
`;
}

function renderOverviewStory() {
  return `/* eslint-disable -- generated by scripts/generate-stories.mjs */
import type { Meta, StoryObj } from '@storybook/react';
import { expect, within } from '@storybook/test';
import { OverviewExample } from '../../examples/components.js';

const meta = {
  title: 'Gallery/Overview',
  component: OverviewExample,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component: 'Full component gallery for visual regression and smoke testing.',
      },
    },
  },
} satisfies Meta<typeof OverviewExample>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const SmokeTest: Story = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    await expect(canvas.getByRole('heading', { name: 'M3UI Component Gallery' })).toBeVisible();
    await expect(canvas.getByTestId('demo-buttons')).toBeVisible();
    await expect(canvas.getByTestId('demo-phase3-nav')).toBeVisible();
    await expect(canvas.getByTestId('demo-nav-bar-compact')).toBeVisible();
    await expect(canvas.getByTestId('demo-carousel-compact')).toBeVisible();
    await expect(canvas.getByTestId('demo-phase4')).toBeVisible();
    await expect(canvas.getByTestId('demo-phase5')).toBeVisible();
  },
};
`;
}

function loadSharedExampleMetadata(slug) {
  const modulePath = join(REPO_ROOT, 'packages/examples/src', `${slug}.examples.tsx`);
  try {
    const source = readFileSync(modulePath, 'utf8');
    const examples = [];
    const titleRe = /title:\s*'([^']+)'/g;
    let match;
    while ((match = titleRe.exec(source)) !== null) {
      examples.push({ title: match[1] });
    }
    return examples;
  } catch {
    return [{ title: 'Default' }];
  }
}

const catalog = loadDocsCatalog();
const sharedExampleSlugs = loadSharedExampleSlugs();

mkdirSync(GENERATED_DIR, { recursive: true });
writeFileSync(join(GENERATED_DIR, 'overview.stories.tsx'), renderOverviewStory());

for (const entry of catalog) {
  const filename = `${entry.slug}.stories.tsx`;
  if (sharedExampleSlugs.has(entry.slug)) {
    const sharedExamples = loadSharedExampleMetadata(entry.slug);
    writeFileSync(
      join(GENERATED_DIR, filename),
      renderSharedExampleStoryFile(entry, sharedExamples),
    );
  } else {
    writeFileSync(join(GENERATED_DIR, filename), renderLegacyStoryFile(entry));
  }
}

console.log(
  `Generated ${catalog.length + 1} Storybook story files from docs-catalog.json (${sharedExampleSlugs.size} shared example slugs)`,
);
