import { FoundationPage } from '@/components/foundation-page';

export default function ColorPage() {
  return <FoundationPage title="Color" description="Dynamic expressive schemes built from semantic roles, not fixed brand swatches." sections={[
    { title: 'Role before value', body: <p>Use system roles such as primary, surface container, and on-surface. The provider generates light and dark roles from one seed and keeps each preview scoped.</p> },
    { title: 'Contrast', body: <p>Standard, medium, and high contrast schemes are generated by Material Color Utilities. Foreground and container roles must remain paired.</p> },
    { title: 'Fixed roles', body: <p>Primary, secondary, and tertiary fixed roles remain stable across light and dark schemes when a design needs invariant emphasis.</p> },
  ]} />;
}
