import type { CatalogCategory, CatalogRegistryType, CatalogStatus, ComponentCatalogEntry } from './types.js';

interface UiCatalogOptions {
  status?: CatalogStatus;
  registryDependencies?: string[];
  related?: string[];
  docs?: Partial<ComponentCatalogEntry['docs']>;
}

function registryUi(
  slug: string,
  sourceFile: string,
  title: string,
  description: string,
  category: CatalogCategory,
  npmDependencies: string[],
  exports: string[],
  options: UiCatalogOptions = {},
): ComponentCatalogEntry {
  const status = options.status ?? 'stable';
  return {
    slug,
    title,
    description,
    category,
    status,
    registryType: 'registry:ui',
    sourceFile,
    npmDependencies,
    registryDependencies: options.registryDependencies ?? [],
    exports,
    related: options.related ?? [],
    docs: {
      route: options.docs?.route ?? true,
      publicIndex: options.docs?.publicIndex ?? status !== 'internal',
      hasContent: options.docs?.hasContent ?? false,
    },
  };
}

/**
 * Single source of truth for registry items, docs navigation, and completeness gates.
 * Consumed by `scripts/build-registry.ts` and emitted as `registry/docs-catalog.json`.
 */
export const COMPONENT_CATALOG: ComponentCatalogEntry[] = [
  registryUi(
    'button',
    'button.tsx',
    'Button',
    'M3 Expressive button with press shape morph',
    'actions',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion', '@m3ui/shapes'],
    ['Button'],
    { related: ['icon-button', 'fab', 'button-group'] },
  ),
  registryUi(
    'icon-button',
    'icon-button.tsx',
    'Icon Button',
    'M3 Expressive icon button with toggle support',
    'actions',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion', '@m3ui/shapes'],
    ['IconButton'],
    { related: ['button', 'fab'] },
  ),
  registryUi(
    'fab',
    'fab.tsx',
    'FAB',
    'Floating action button and extended FAB',
    'actions',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Fab', 'ExtendedFab'],
    { related: ['icon-button', 'fab-menu', 'scaffold'] },
  ),
  registryUi(
    'checkbox',
    'checkbox.tsx',
    'Checkbox',
    'Checkbox and checkbox group',
    'selection',
    ['@m3ui/react', '@m3ui/tokens'],
    ['Checkbox', 'CheckboxGroup'],
    { related: ['radio', 'switch'] },
  ),
  registryUi(
    'radio',
    'radio.tsx',
    'Radio',
    'Radio button and radio group',
    'selection',
    ['@m3ui/react', '@m3ui/tokens'],
    ['Radio', 'RadioGroup'],
    { related: ['checkbox', 'switch'] },
  ),
  registryUi(
    'switch',
    'switch.tsx',
    'Switch',
    'M3 Expressive switch with icon slots',
    'selection',
    ['@m3ui/react', '@m3ui/tokens'],
    ['Switch'],
    { related: ['checkbox', 'radio'] },
  ),
  registryUi(
    'text-field',
    'text-field.tsx',
    'Text Field',
    'Filled and outlined text fields with floating labels',
    'inputs',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['TextField'],
    { related: ['select', 'autocomplete', 'search'] },
  ),
  registryUi(
    'card',
    'card.tsx',
    'Card',
    'Elevated, filled, and outlined cards',
    'containment',
    ['@m3ui/react', '@m3ui/tokens'],
    ['Card'],
    { related: ['list', 'carousel'] },
  ),
  registryUi(
    'list',
    'list.tsx',
    'List',
    'M3 list and list items',
    'containment',
    ['@m3ui/react', '@m3ui/tokens'],
    ['List', 'ListItem'],
    { related: ['card', 'divider'] },
  ),
  registryUi(
    'divider',
    'divider.tsx',
    'Divider',
    'Full-width, inset, and vertical dividers',
    'containment',
    ['@m3ui/react', '@m3ui/tokens'],
    ['Divider'],
    { related: ['list'] },
  ),
  registryUi(
    'badge',
    'badge.tsx',
    'Badge',
    'Dot and numbered badges',
    'communication',
    ['@m3ui/react', '@m3ui/tokens'],
    ['Badge'],
    { related: ['navigation-bar', 'icon-button'] },
  ),
  registryUi(
    'tooltip',
    'tooltip.tsx',
    'Tooltip',
    'Plain and rich tooltips',
    'communication',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Tooltip', 'RichTooltip'],
    { related: ['icon-button', 'button'] },
  ),
  registryUi(
    'chip',
    'chip.tsx',
    'Chip',
    'Assist, filter, input, and suggestion chips',
    'selection',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Chip', 'ChipSet', 'FilterChipGroup'],
    { related: ['segmented-button', 'button'] },
  ),
  registryUi(
    'segmented-button',
    'segmented-button.tsx',
    'Segmented Button',
    'Single and multi-select segmented buttons',
    'actions',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['SegmentedButton', 'SegmentedButtonItem'],
    { related: ['button', 'tabs'] },
  ),
  registryUi(
    'slider',
    'slider.tsx',
    'Slider',
    'Continuous, discrete, centered, range, and vertical sliders',
    'selection',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Slider'],
    { related: ['switch', 'meter'] },
  ),
  registryUi(
    'menu',
    'menu.tsx',
    'Menu',
    'Dropdown menu, context menu, and menubar',
    'containment',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Menu', 'MenuItem', 'ContextMenu', 'Menubar', 'MenubarMenu'],
    { related: ['select', 'split-button'] },
  ),
  registryUi(
    'select',
    'select.tsx',
    'Select',
    'M3 exposed dropdown menu styled as text field',
    'selection',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Select', 'ExposedDropdownMenu'],
    { related: ['menu', 'text-field', 'autocomplete'] },
  ),
  registryUi(
    'autocomplete',
    'autocomplete.tsx',
    'Autocomplete',
    'Autocomplete and combobox with M3 text field styling',
    'inputs',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Autocomplete', 'Combobox'],
    { related: ['text-field', 'select', 'search'] },
  ),
  registryUi(
    'progress',
    'progress.tsx',
    'Progress',
    'Linear and circular progress with wavy Expressive variants',
    'feedback',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Progress', 'LinearProgress', 'CircularProgress'],
    { related: ['loading-indicator', 'meter'] },
  ),
  registryUi(
    'loading-indicator',
    'loading-indicator.tsx',
    'Loading Indicator',
    'Expressive shape-cycling loader',
    'feedback',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion', '@m3ui/shapes'],
    ['LoadingIndicator'],
    { related: ['progress', 'shapes'] },
  ),
  registryUi(
    'snackbar',
    'snackbar.tsx',
    'Snackbar',
    'Toast snackbars with queueing and positioning',
    'communication',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Snackbar', 'SnackbarProvider', 'useSnackbar'],
    { related: ['dialog', 'bottom-sheet'] },
  ),
  registryUi(
    'meter',
    'meter.tsx',
    'Meter',
    'Meter styled consistently with progress indicators',
    'feedback',
    ['@m3ui/react', '@m3ui/tokens'],
    ['Meter'],
    { related: ['progress', 'slider'] },
  ),
  registryUi(
    'top-app-bar',
    'top-app-bar.tsx',
    'Top App Bar',
    'Small, medium, large, and flexible Expressive top app bars',
    'navigation',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['TopAppBar'],
    { related: ['scaffold', 'navigation-bar', 'search'] },
  ),
  registryUi(
    'bottom-app-bar',
    'bottom-app-bar.tsx',
    'Bottom App Bar',
    'Bottom app bar with action slots and attached FAB',
    'navigation',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['BottomAppBar'],
    { related: ['navigation-bar', 'fab', 'scaffold'] },
  ),
  registryUi(
    'navigation-bar',
    'navigation-bar.tsx',
    'Navigation Bar',
    'Bottom navigation bar with active indicator pill and badges',
    'navigation',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['NavigationBar'],
    { related: ['navigation-rail', 'adaptive-navigation'] },
  ),
  registryUi(
    'navigation-rail',
    'navigation-rail.tsx',
    'Navigation Rail',
    'Collapsed, expanded, and modal navigation rail',
    'navigation',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['NavigationRail'],
    { related: ['navigation-drawer', 'adaptive-navigation'] },
  ),
  registryUi(
    'navigation-drawer',
    'navigation-drawer.tsx',
    'Navigation Drawer',
    'Standard and modal navigation drawer with sections',
    'navigation',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['NavigationDrawer', 'NavigationDrawerTrigger'],
    { related: ['navigation-rail', 'adaptive-navigation'] },
  ),
  registryUi(
    'tabs',
    'tabs.tsx',
    'Tabs',
    'Primary and secondary tabs with scrollable layout',
    'containment',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Tabs', 'TabsPrimitive'],
    { related: ['segmented-button', 'carousel'] },
  ),
  registryUi(
    'search',
    'search.tsx',
    'Search',
    'Search bar and full-screen search view',
    'inputs',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['SearchBar', 'SearchView'],
    { related: ['text-field', 'autocomplete', 'top-app-bar'] },
  ),
  registryUi(
    'dialog',
    'dialog.tsx',
    'Dialog',
    'Dialog, alert dialog, and full-screen dialog',
    'containment',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Dialog', 'AlertDialog', 'FullScreenDialog', 'DialogAction'],
    { related: ['bottom-sheet', 'side-sheet', 'snackbar'] },
  ),
  registryUi(
    'bottom-sheet',
    'bottom-sheet.tsx',
    'Bottom Sheet',
    'Modal bottom sheet with snap points and drag handle',
    'containment',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['BottomSheet'],
    { related: ['dialog', 'side-sheet'] },
  ),
  registryUi(
    'side-sheet',
    'side-sheet.tsx',
    'Side Sheet',
    'Side sheet with header and action row',
    'containment',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['SideSheet'],
    { related: ['dialog', 'bottom-sheet', 'navigation-drawer'] },
  ),
  registryUi(
    'carousel',
    'carousel.tsx',
    'Carousel',
    'M3 carousel layouts with scroll-linked resize',
    'containment',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Carousel'],
    { related: ['card', 'tabs'] },
  ),
  registryUi(
    'scaffold',
    'scaffold.tsx',
    'Scaffold',
    'App layout composing chrome with inset CSS variables',
    'layout',
    ['@m3ui/react', '@m3ui/tokens'],
    ['Scaffold', 'FabAnchor'],
    { related: ['top-app-bar', 'pane-scaffold', 'adaptive-navigation'] },
  ),
  registryUi(
    'button-group',
    'button-group.tsx',
    'Button Group',
    'Standard and connected button groups with neighbor bump',
    'actions',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion', '@m3ui/shapes'],
    ['ButtonGroup', 'ButtonGroupItem'],
    { related: ['button', 'split-button', 'segmented-button'] },
  ),
  registryUi(
    'split-button',
    'split-button.tsx',
    'Split Button',
    'Leading action with trailing menu trigger',
    'actions',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion', '@m3ui/shapes'],
    ['SplitButton'],
    { related: ['button', 'menu', 'button-group'] },
  ),
  registryUi(
    'fab-menu',
    'fab-menu.tsx',
    'FAB Menu',
    'FAB expanding to labeled action list',
    'actions',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion', '@m3ui/shapes'],
    ['FabMenu'],
    { related: ['fab', 'menu'] },
  ),
  registryUi(
    'toolbar',
    'toolbar.tsx',
    'Toolbar',
    'Docked and floating toolbars with scroll hide/show',
    'actions',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['Toolbar', 'ToolbarButton'],
    { related: ['top-app-bar', 'button-group'] },
  ),
  registryUi(
    'date-input',
    'date-input.tsx',
    'Date Input',
    'Locale-aware date input with Field validation',
    'pickers',
    ['@m3ui/react', '@m3ui/tokens', '@internationalized/date'],
    ['DateInput'],
    { related: ['date-picker', 'text-field'] },
  ),
  registryUi(
    'date-picker',
    'date-picker.tsx',
    'Date Picker',
    'Docked, modal, and range date pickers with calendar engine',
    'pickers',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion', '@internationalized/date'],
    ['DatePicker'],
    { related: ['date-input', 'time-picker'] },
  ),
  registryUi(
    'time-picker',
    'time-picker.tsx',
    'Time Picker',
    'Dial and input time pickers with 12h/24h support',
    'pickers',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['TimePicker'],
    { related: ['date-picker', 'date-input'] },
  ),
  registryUi(
    'pane-scaffold',
    'pane-scaffold.tsx',
    'Pane Scaffold',
    'List-detail and supporting-pane adaptive layouts',
    'layout',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['PaneScaffold', 'PaneScaffoldRoot'],
    { related: ['scaffold', 'adaptive-navigation'] },
  ),
  registryUi(
    'adaptive-navigation',
    'adaptive-navigation.tsx',
    'Adaptive Navigation',
    'Auto-switching navigation bar, rail, and drawer',
    'navigation',
    ['@m3ui/react', '@m3ui/tokens', '@m3ui/motion'],
    ['AdaptiveNavigation', 'resolveAdaptiveNavMode'],
    { related: ['navigation-bar', 'navigation-rail', 'navigation-drawer', 'scaffold'] },
  ),
  registryUi(
    'placeholder-button',
    'placeholder-button.tsx',
    'Placeholder Button',
    'Registry placeholder for install testing',
    'actions',
    ['@m3ui/react', '@m3ui/tokens'],
    ['PlaceholderButton'],
    {
      status: 'internal',
      docs: { route: true, publicIndex: false },
    },
  ),
  {
    slug: 'shapes',
    title: 'Shapes',
    description: 'Material Design 3 Expressive shape morphing, ShapeCrop, and the shapes library',
    category: 'foundations',
    status: 'stable',
    registryType: 'foundations',
    npmDependencies: ['@m3ui/shapes', '@m3ui/react', '@m3ui/tokens'],
    registryDependencies: [],
    exports: ['ShapeCrop', 'MaterialShapes'],
    related: ['button', 'loading-indicator', 'button-group'],
    docs: {
      route: true,
      publicIndex: true,
      hasContent: false,
    },
  },
];

export function getCatalogEntry(slug: string): ComponentCatalogEntry | undefined {
  return COMPONENT_CATALOG.find((entry) => entry.slug === slug);
}

export function getRegistryUiEntries(): ComponentCatalogEntry[] {
  return COMPONENT_CATALOG.filter((entry) => entry.registryType === 'registry:ui');
}

export function getPublicCatalogEntries(): ComponentCatalogEntry[] {
  return COMPONENT_CATALOG.filter(
    (entry) => entry.status !== 'internal' && entry.docs.publicIndex,
  );
}

export function getCatalogEntriesByCategory(category: CatalogCategory): ComponentCatalogEntry[] {
  return COMPONENT_CATALOG.filter((entry) => entry.category === category);
}
